# Generated by Django 4.2.3 on 2023-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=30)),
                ('L_Name', models.CharField(max_length=30)),
                ('V_Name', models.CharField(max_length=40)),
                ('S_Id', models.IntegerField()),
                ('S_Cgpa', models.FloatField()),
                ('S_Age', models.IntegerField()),
            ],
        ),
    ]
