# Generated by Django 4.2.3 on 2023-07-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Versity_Name', models.CharField(max_length=40)),
                ('Student_Mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
