# Generated by Django 4.2.3 on 2023-07-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0002_second_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='first_table',
            table='First_Table',
        ),
    ]
